spring.application.name: maple-api
server:
  port: 8080
  shutdown: graceful


spring:
  # graceful shutdown ??
  lifecycle:
    timeout-per-shutdown-phase: 5s

  datasource:
    url: jdbc:postgresql://localhost:5432/maple_db
    username: maple_username
    password: maple_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 1000
        # ????? insert? update? ???? ????? ??
        order_updates: true
        order_inserts: true
        jdbc:
          # insert/update? ??? ?? ??
          batch_size: 1000
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://192.168.45.205:8080/login/oauth2/code/kakao
            client-id: 4d931a5ba1ff89881779dfd513f4bfa4
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

management:
  server.port: 8080
  endpoints.enabled-by-default: false
  endpoints.web.exposure.include: info, health
  endpoint.info.enabled: true
  endpoint.health.enabled: true

jwt:
  secret: JTh4bhwwq69/Cj9gDLDXh8Riktoi9ndjD5T0cfHeSWkyC1aE7Xk2XpcDxwbk3Yyotj9d007VxNQuOYMjRoXMzg==
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    com.maple.api: DEBUG
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    #    url: ${DB_URL}
    #    username: ${DB_USERNAME}
    #    password: ${DB_PASSWORD}

    driver-class-name: org.postgresql.Driver